/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GoBackBtn: (typeof import('./components/GoBackBtn.vue'))['default'];
    Home: (typeof import('./components/Home.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SecretForm: (typeof import('./components/SecretForm.vue'))['default'];
    SecretView: (typeof import('./components/SecretView.vue'))['default'];
  }
}
